// Faça um Programa que peça dois números e imprima o maior deles, e informe caso eles sejam iguais.


var prompt = require("prompt-sync")();

valor1 = +prompt("DIGITE UM VALOR:  ");
valor2 = +prompt("DIGITE OUTRO VALOR:   ");

if (valor1 === valor2){;
    console.log("");
    console.log("PARABÉNS SEUS VALORES SÃO IGUAIS");
    console.log("");
}else{;
    console.log("");
    console.log("SÃO VALORES DIFERENTES");
    console.log("")};