//7) E os 10% do garçom? - Defina uma variável para o valor de uma refeição que custou R$ 42,54. 
//Na sequência, defina uma variável para o valor da taxa de serviço que é de 10%. Por fim defina uma variável 
//que será responsável pelo cálculo do valor total da conta e exiba-o no console com a seguinte formatação: 
//R$99.99 (valor com duas casas decimais).


var prato = 42.5
var taxa = 42.5 * 0.1
var preçot = prato + taxa


console.log("VALOR DO PRATO É:", prato)
console.log("VALOR DA TAXA É:", taxa)
console.log("PREÇO TOTAL É",preçot.toFixed(2))
console.log("")
