// 3) Letra de Música - Faça um programa que mostre na tela uma letra de música que você gosta.

console.log(`Tears on the mausoleum floor
Blood stains the Coliseum doors
Blood stains the Coliseum doors
Lies on the lips of a priest
Thanksgiving disguised as a feast
Rollin in the Rolls-Royce Corniche
Only the doctors got this, Im hidin from police
Cocaine seats
All white like I got the whole thing bleached
Drug dealer chic
Im wonderin if a thugs prayers reach
Is Pious pious cause God loves pious?
Socrates asks, Whose bias do y'all seek?
All for Plato, screech
Im out chere ballin, I know yall hear my sneaks
Jesus was a carpenter, Yeezy, laid beats
Hova flow the Holy Ghost, get the hell up out your seats, preac
Blood stains the Coliseum doors
Blood stains the Coliseum doors`)

// USAR A CRASE ( ` )